package com.trilogy.app.crm.bean.paymentgatewayintegration;

import java.io.BufferedReader;
import java.io.EOFException;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.IllegalFormatWidthException;

import com.trilogy.app.crm.bean.CurrencyPrecision;
import com.trilogy.app.crm.bean.IdentifierEnum;
import com.trilogy.app.crm.support.IdentifierSequenceSupportHelper;
import com.trilogy.framework.xhome.context.Context;
import com.trilogy.framework.xhome.home.HomeException;
import com.trilogy.framework.xlog.log.MinorLogMsg;

public class AdmerisDirectDebitOutboundFileReader 
{


	public AdmerisDirectDebitOutboundFileReader()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
	{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

	synchronized public void init(Context ctx, String fileName)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
			throws Exception                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
			{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		if (this.input == null )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
			this.lineCount = 0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
			this.totalAmount = 0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			this.fileName  = fileName;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
			this.input = new BufferedReader(new FileReader(new  File(this.fileName)));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
			this.readHeader();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
			}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

	synchronized public void close(Context ctx)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		if (this.input != null)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
		{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
			try {
				this.input.close();
			} 
			catch (IOException e) 
			{
				//DO Nothing
				new MinorLogMsg(this, "Exception encountered while closing the File." , e).log(ctx);
			}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

	private void readHeader() throws IOException                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
	{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		input.readLine();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
	}     

	public String readRecord() throws IOException
	{
		String record;

		record = input.readLine();


		if(record == null || "99".equals(record.substring(0,2)))
		{
			throw new EOFException();
		}

//		if(record.length() != TOTAL_REOORD_LENGTH)
//		{
//			throw new IllegalFormatWidthException(TOTAL_REOORD_LENGTH);
//			throw new Illegalarg
//		}

		return record;
	}


	public static String getBan(Context ctx, String record) {

		int startIndex = SEQUENCE_NUMBER_LENGTH + PAYMETN_MODE_LENGTH + DD_INDICATOR_LENGTH;
		int endIndex  = startIndex + CUSTOMER_ACCOUNT_NUMBER_LENGTH;
		if(record.length() >= endIndex)
		{
			return record.substring(startIndex, endIndex ).trim();
		}
		else
		{
			return null;
		}
	}

	public static long getAmount(Context ctx, String record, CurrencyPrecision precision) {

		int startIndex = SEQUENCE_NUMBER_LENGTH		
				+PAYMETN_MODE_LENGTH		
				+DD_INDICATOR_LENGTH		
				+CUSTOMER_ACCOUNT_NUMBER_LENGTH	
				+BILL_NUMBER_LENGTH		
				+BANK_CODE_LENGTH;

		int endIndex  = startIndex + BILL_AMOUNT_LENGTH;
		if(record.length() >= endIndex)
		{
			String amountStr = record.substring(startIndex, endIndex ).trim();
			return ((new BigDecimal(amountStr)).multiply(new BigDecimal(Math.pow(10, precision.getStoragePrecision()))).longValue());

		}
		else
		{
			return 0;
		}
	}
	
	public boolean verifyLength(Context ctx, String record) {
		
		if(record.length() == TOTAL_REOORD_LENGTH)
		{
			return true;
		}
		else
		{
			return false;
		}
	}



	String fileName = "";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
	BufferedReader input = null;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
	long totalAmount = 0l;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
	long lineCount = 0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             


	public static final int  SEQUENCE_NUMBER_LENGTH = 10;
	public static final int  PAYMETN_MODE_LENGTH = 2;
	public static final int  DD_INDICATOR_LENGTH = 2;
	public static final int  CUSTOMER_ACCOUNT_NUMBER_LENGTH = 21;
	public static final int  BILL_NUMBER_LENGTH = 16;
	public static final int  BANK_CODE_LENGTH = 5;
	public static final int  BILL_AMOUNT_LENGTH = 12;
	public static final int  BILL_DUE_DATE_LENGTH = 10;
	public static final int  CC_NUMBER_LENGTH = 20;
	public static final int  CC_EXPIRY_LENGTH = 10;
	public static final int  CC_NAME_LENGTH = 50;
	public static final int  CUSTOMER_ACCOUNT_NAME_LENGTH = 150;
	public static final int  TOTAL_REOORD_LENGTH = 308;
	

}
